# fly.toml app configuration file generated for hagar-is-cooking on 2026-07-02T13:16:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hagar-is-cooking'
primary_region = 'ams'

[build]

[env]
  DATABASE_PATH = '/data/hagar_is_cooking.db'
  LOG_LEVEL = 'INFO'

[[mounts]]
  source = 'hagar_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
